const ENTRIES = [
  "Found a frozen ledger in the lobby. The columns survived. I did not.",
  "The fax machine works. No one is faxing.",
  "Auditor's thermos in the breakroom. Still warm. Did not investigate.",
  "Snow on the printer. The toner cartridge says: CHANGE ME.",
  "Wind through the cubicles. A stapler answers.",
  "Slept in the file room. Dreamed about FIFO.",
  "Calendar on the wall reads March. Outside it is March of some year.",
  "Today's lunch: half a granola bar and a tax-loss carryforward.",
  "The CFO's chair still spins. The CFO does not.",
  "Form 1099 alphabetized. I am proud of myself.",
  "Heard wolves. They were the HVAC.",
  "Found a working pen. Will use sparingly.",
  "There is a Post-it on my desk. It reads: RECONCILE.",
  "The vending machine took my last quarter and gave me grace.",
  "Three filing cabinets, one survivor: me.",
  "Memo to self: prepaid means PAID. Past tense. Like everything.",
  "The ledger has a coffee ring. Don't they all.",
  "Spent the morning reconciling. Spent the afternoon shivering.",
  "Stapler is fine. We are companions now.",
  "Trial balance is the same as me — not quite balancing.",
  "Reorganized the supply closet by relevance. The toner won.",
  "Frost on the inside of the windows is a feature.",
  "Audit committee met in my head. Three of them voted to keep going.",
  "Found a calculator with a working solar panel. I named it Hope.",
  "Dating the office plant. It is dead. So am I.",
  "The break room microwave is also a heater. Discovered this by accident.",
  "Internal control: the door no longer closes.",
  "Materiality threshold updated to: matters to me.",
  "Saw a deer in the parking lot. Did not invoice it.",
  "Backed up the books to a flash drive. The drive is in my sock.",
  "Counted the days. Twice. They reconcile.",
  "Auditor's notes from last year, found behind a vent: \"OK.\"",
  "Wrote a journal entry today. Two journal entries, if you count this one.",
  "The whiteboard says Q1 GOALS. I am not crossing them out.",
];

export const journalEntry = (day: number): string => {
  return ENTRIES[(day * 13 + 7) % ENTRIES.length];
};
